// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/protobuf/message/product.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	app/protobuf/message/product.proto

It has these top-level messages:
	Active
	ProductRequest
	ProductResponse
	ProductResponses
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Active struct {
	Active bool `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
}

func (m *Active) Reset()                    { *m = Active{} }
func (m *Active) String() string            { return proto.CompactTextString(m) }
func (*Active) ProtoMessage()               {}
func (*Active) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Active) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ProductRequest struct {
	Id        int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Price     float32 `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Image     string  `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Active    *Active `protobuf:"bytes,5,opt,name=active" json:"active,omitempty"`
	CreatedAt int64   `protobuf:"varint,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt int64   `protobuf:"varint,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt int64   `protobuf:"varint,8,opt,name=deletedAt" json:"deletedAt,omitempty"`
	Limit     int32   `protobuf:"varint,9,opt,name=limit" json:"limit,omitempty"`
	Offset    int32   `protobuf:"varint,10,opt,name=offset" json:"offset,omitempty"`
}

func (m *ProductRequest) Reset()                    { *m = ProductRequest{} }
func (m *ProductRequest) String() string            { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()               {}
func (*ProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProductRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ProductRequest) GetActive() *Active {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *ProductRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ProductRequest) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ProductRequest) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *ProductRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ProductRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ProductResponse struct {
	Id        int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Price     float32 `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Image     string  `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Active    *Active `protobuf:"bytes,5,opt,name=active" json:"active,omitempty"`
	CreatedAt int64   `protobuf:"varint,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt int64   `protobuf:"varint,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt int64   `protobuf:"varint,8,opt,name=deletedAt" json:"deletedAt,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProductResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ProductResponse) GetActive() *Active {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *ProductResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ProductResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *ProductResponse) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type ProductResponses struct {
	ProductResponses []*ProductResponse `protobuf:"bytes,1,rep,name=productResponses" json:"productResponses,omitempty"`
}

func (m *ProductResponses) Reset()                    { *m = ProductResponses{} }
func (m *ProductResponses) String() string            { return proto.CompactTextString(m) }
func (*ProductResponses) ProtoMessage()               {}
func (*ProductResponses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProductResponses) GetProductResponses() []*ProductResponse {
	if m != nil {
		return m.ProductResponses
	}
	return nil
}

func init() {
	proto.RegisterType((*Active)(nil), "product.message.Active")
	proto.RegisterType((*ProductRequest)(nil), "product.message.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "product.message.ProductResponse")
	proto.RegisterType((*ProductResponses)(nil), "product.message.ProductResponses")
}

func init() { proto.RegisterFile("app/protobuf/message/product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x92, 0x41, 0x6e, 0xea, 0x30,
	0x10, 0x86, 0xe5, 0x00, 0x79, 0x30, 0x48, 0x80, 0xac, 0xa7, 0xd6, 0x8b, 0x2e, 0xac, 0x48, 0x55,
	0xb3, 0x81, 0x48, 0xf4, 0x04, 0x74, 0xdd, 0x45, 0xe5, 0x65, 0x57, 0x35, 0xf1, 0x80, 0x2c, 0x11,
	0xe2, 0xc6, 0x0e, 0x77, 0xe9, 0x1d, 0x7b, 0x88, 0xca, 0x76, 0x48, 0xa5, 0x70, 0x83, 0xee, 0xfc,
	0x7f, 0x9f, 0x47, 0xf9, 0x33, 0x32, 0x64, 0xd2, 0x98, 0xc2, 0x34, 0xb5, 0xab, 0xf7, 0xed, 0xa1,
	0xa8, 0xd0, 0x5a, 0x79, 0x44, 0x0f, 0x54, 0x5b, 0xba, 0x4d, 0x10, 0x74, 0x79, 0x8d, 0x9d, 0xce,
	0x38, 0xa4, 0xbb, 0xd2, 0xe9, 0x0b, 0xd2, 0x3b, 0x48, 0x65, 0x38, 0x31, 0xc2, 0x49, 0x3e, 0x15,
	0x5d, 0xca, 0xbe, 0x12, 0x58, 0xbc, 0xc5, 0x29, 0x81, 0x9f, 0x2d, 0x5a, 0x47, 0x17, 0x90, 0x68,
	0x15, 0xae, 0x8d, 0x44, 0xa2, 0x15, 0xa5, 0x30, 0x3e, 0xcb, 0x0a, 0x59, 0xc2, 0x49, 0x3e, 0x13,
	0xe1, 0x4c, 0xff, 0xc3, 0xc4, 0x34, 0xba, 0x44, 0x36, 0xe2, 0x24, 0x4f, 0x44, 0x0c, 0x9e, 0xea,
	0x4a, 0x1e, 0x91, 0x8d, 0xc3, 0xd5, 0x18, 0x68, 0xd1, 0x7f, 0x7a, 0xc2, 0x49, 0x3e, 0xdf, 0xde,
	0x6f, 0x06, 0x35, 0x37, 0xb1, 0xe3, 0xb5, 0x13, 0x7d, 0x80, 0x59, 0xd9, 0xa0, 0x74, 0xa8, 0x76,
	0x8e, 0xa5, 0xa1, 0xc7, 0x2f, 0xf0, 0xb6, 0x35, 0xaa, 0xb3, 0xff, 0xa2, 0xed, 0x81, 0xb7, 0x0a,
	0x4f, 0x18, 0xed, 0x34, 0xda, 0x1e, 0xf8, 0x82, 0x27, 0x5d, 0x69, 0xc7, 0x66, 0x9c, 0xe4, 0x13,
	0x11, 0x83, 0xdf, 0x4d, 0x7d, 0x38, 0x58, 0x74, 0x0c, 0x02, 0xee, 0x52, 0xf6, 0x4d, 0x60, 0xd9,
	0xef, 0xc6, 0x9a, 0xfa, 0x6c, 0xf1, 0x0f, 0x2f, 0x27, 0xfb, 0x80, 0xd5, 0xe0, 0x6f, 0x2d, 0x7d,
	0x85, 0x95, 0x19, 0x30, 0x46, 0xf8, 0x28, 0x9f, 0x6f, 0xf9, 0x4d, 0xd1, 0xc1, 0xb0, 0xb8, 0x99,
	0x7c, 0x79, 0x7a, 0x7f, 0xec, 0xd8, 0xda, 0x62, 0x73, 0xd1, 0x25, 0x16, 0xfd, 0xab, 0x5e, 0x1f,
	0xf1, 0x7c, 0x7d, 0xd6, 0xfb, 0x34, 0xa0, 0xe7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xf9,
	0xc7, 0x5a, 0xf5, 0x02, 0x00, 0x00,
}
