server:
  host: 127.0.0.1
  port: 7000
  timeout: 30000

postgres:
  host: 127.0.0.1
  port: 5432
  userName: postgres
  password: root
  database: health

elasticsearch:
  host: 127.0.0.1
  port: 9200
  userName: elastics
  password: elastics