// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/protobuf/message/promotion.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	app/protobuf/message/promotion.proto

It has these top-level messages:
	Active
	PromotionRequest
	PromotionResponse
	PromotionResponses
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Active struct {
	Active bool `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
}

func (m *Active) Reset()                    { *m = Active{} }
func (m *Active) String() string            { return proto.CompactTextString(m) }
func (*Active) ProtoMessage()               {}
func (*Active) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Active) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type PromotionRequest struct {
	Id        int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Price     float32 `protobuf:"fixed32,3,opt,name=price" json:"price,omitempty"`
	Image     string  `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	Active    *Active `protobuf:"bytes,5,opt,name=active" json:"active,omitempty"`
	CreatedAt int64   `protobuf:"varint,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt int64   `protobuf:"varint,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt int64   `protobuf:"varint,8,opt,name=deletedAt" json:"deletedAt,omitempty"`
	Limit     int32   `protobuf:"varint,9,opt,name=limit" json:"limit,omitempty"`
	Offset    int32   `protobuf:"varint,10,opt,name=offset" json:"offset,omitempty"`
}

func (m *PromotionRequest) Reset()                    { *m = PromotionRequest{} }
func (m *PromotionRequest) String() string            { return proto.CompactTextString(m) }
func (*PromotionRequest) ProtoMessage()               {}
func (*PromotionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PromotionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PromotionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PromotionRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PromotionRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PromotionRequest) GetActive() *Active {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *PromotionRequest) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PromotionRequest) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *PromotionRequest) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *PromotionRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PromotionRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type PromotionResponse struct {
	Id                     int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Code                   string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	PromotionType          string  `protobuf:"bytes,3,opt,name=promotionType" json:"promotionType,omitempty"`
	Value                  float32 `protobuf:"fixed32,4,opt,name=value" json:"value,omitempty"`
	Image                  string  `protobuf:"bytes,5,opt,name=image" json:"image,omitempty"`
	Active                 *Active `protobuf:"bytes,6,opt,name=active" json:"active,omitempty"`
	CreatedBy              int32   `protobuf:"varint,7,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedAt              int64   `protobuf:"varint,8,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt              int64   `protobuf:"varint,9,opt,name=updatedAt" json:"updatedAt,omitempty"`
	DeletedAt              int64   `protobuf:"varint,10,opt,name=deletedAt" json:"deletedAt,omitempty"`
	ActiveFrom             int64   `protobuf:"varint,11,opt,name=activeFrom" json:"activeFrom,omitempty"`
	ActiveTo               int64   `protobuf:"varint,12,opt,name=activeTo" json:"activeTo,omitempty"`
	DailyActiveFrom        int64   `protobuf:"varint,13,opt,name=dailyActiveFrom" json:"dailyActiveFrom,omitempty"`
	DailyActiveTo          int32   `protobuf:"varint,14,opt,name=dailyActiveTo" json:"dailyActiveTo,omitempty"`
	MaxActiveTime          int32   `protobuf:"varint,15,opt,name=maxActiveTime" json:"maxActiveTime,omitempty"`
	MaxDailyActiveTime     int32   `protobuf:"varint,16,opt,name=maxDailyActiveTime" json:"maxDailyActiveTime,omitempty"`
	PerUserActiveTime      int32   `protobuf:"varint,17,opt,name=perUserActiveTime" json:"perUserActiveTime,omitempty"`
	PerUserDailyActiveTime int32   `protobuf:"varint,18,opt,name=perUserDailyActiveTime" json:"perUserDailyActiveTime,omitempty"`
}

func (m *PromotionResponse) Reset()                    { *m = PromotionResponse{} }
func (m *PromotionResponse) String() string            { return proto.CompactTextString(m) }
func (*PromotionResponse) ProtoMessage()               {}
func (*PromotionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PromotionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PromotionResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PromotionResponse) GetPromotionType() string {
	if m != nil {
		return m.PromotionType
	}
	return ""
}

func (m *PromotionResponse) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *PromotionResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PromotionResponse) GetActive() *Active {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *PromotionResponse) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *PromotionResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PromotionResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *PromotionResponse) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *PromotionResponse) GetActiveFrom() int64 {
	if m != nil {
		return m.ActiveFrom
	}
	return 0
}

func (m *PromotionResponse) GetActiveTo() int64 {
	if m != nil {
		return m.ActiveTo
	}
	return 0
}

func (m *PromotionResponse) GetDailyActiveFrom() int64 {
	if m != nil {
		return m.DailyActiveFrom
	}
	return 0
}

func (m *PromotionResponse) GetDailyActiveTo() int32 {
	if m != nil {
		return m.DailyActiveTo
	}
	return 0
}

func (m *PromotionResponse) GetMaxActiveTime() int32 {
	if m != nil {
		return m.MaxActiveTime
	}
	return 0
}

func (m *PromotionResponse) GetMaxDailyActiveTime() int32 {
	if m != nil {
		return m.MaxDailyActiveTime
	}
	return 0
}

func (m *PromotionResponse) GetPerUserActiveTime() int32 {
	if m != nil {
		return m.PerUserActiveTime
	}
	return 0
}

func (m *PromotionResponse) GetPerUserDailyActiveTime() int32 {
	if m != nil {
		return m.PerUserDailyActiveTime
	}
	return 0
}

type PromotionResponses struct {
	PromotionResponses []*PromotionResponse `protobuf:"bytes,1,rep,name=promotionResponses" json:"promotionResponses,omitempty"`
}

func (m *PromotionResponses) Reset()                    { *m = PromotionResponses{} }
func (m *PromotionResponses) String() string            { return proto.CompactTextString(m) }
func (*PromotionResponses) ProtoMessage()               {}
func (*PromotionResponses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PromotionResponses) GetPromotionResponses() []*PromotionResponse {
	if m != nil {
		return m.PromotionResponses
	}
	return nil
}

func init() {
	proto.RegisterType((*Active)(nil), "promotion.message.Active")
	proto.RegisterType((*PromotionRequest)(nil), "promotion.message.PromotionRequest")
	proto.RegisterType((*PromotionResponse)(nil), "promotion.message.PromotionResponse")
	proto.RegisterType((*PromotionResponses)(nil), "promotion.message.PromotionResponses")
}

func init() { proto.RegisterFile("app/protobuf/message/promotion.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0xb1, 0xf3, 0xd3, 0xe4, 0xa6, 0xf3, 0x13, 0x51, 0x06, 0xb5, 0x94, 0x62, 0x42, 0x16,
	0x5e, 0x74, 0x12, 0x66, 0x06, 0xba, 0xcf, 0x50, 0xba, 0x2e, 0x22, 0xdd, 0x74, 0xa7, 0x89, 0x6f,
	0x82, 0x4a, 0x6c, 0xa9, 0x96, 0x12, 0x26, 0x0f, 0xd3, 0x37, 0xed, 0xa2, 0x48, 0x72, 0x6c, 0x27,
	0x76, 0x07, 0x66, 0xa7, 0xf3, 0x9d, 0x73, 0xed, 0xeb, 0x83, 0x11, 0x4c, 0xb9, 0x52, 0x73, 0x95,
	0x4b, 0x23, 0x9f, 0x76, 0xeb, 0x79, 0x8a, 0x5a, 0xf3, 0x0d, 0x5a, 0x90, 0x4a, 0x23, 0x64, 0x36,
	0x73, 0x16, 0x19, 0x57, 0xa0, 0x88, 0x4c, 0x22, 0xe8, 0x2f, 0x56, 0x46, 0xec, 0x91, 0xdc, 0x40,
	0x9f, 0xbb, 0x13, 0x0d, 0xa2, 0x20, 0x1e, 0xb0, 0x42, 0x4d, 0xfe, 0x84, 0x70, 0xfd, 0xfd, 0x38,
	0xc7, 0xf0, 0xf7, 0x0e, 0xb5, 0x21, 0x97, 0x10, 0x8a, 0xc4, 0x05, 0x3b, 0x2c, 0x14, 0x09, 0x21,
	0xd0, 0xcd, 0x78, 0x8a, 0x34, 0x8c, 0x82, 0x78, 0xc8, 0xdc, 0x99, 0xbc, 0x83, 0x9e, 0xca, 0xc5,
	0x0a, 0x69, 0x27, 0x0a, 0xe2, 0x90, 0x79, 0x61, 0xa9, 0x48, 0xf9, 0x06, 0x69, 0xd7, 0x45, 0xbd,
	0x20, 0x77, 0xe5, 0xcb, 0x7b, 0x51, 0x10, 0x8f, 0xee, 0xdf, 0xcf, 0x1a, 0xab, 0xce, 0xfc, 0x9e,
	0xc7, 0xbd, 0xc8, 0x47, 0x18, 0xae, 0x72, 0xe4, 0x06, 0x93, 0x85, 0xa1, 0x7d, 0xb7, 0x49, 0x05,
	0xac, 0xbb, 0x53, 0x49, 0xe1, 0xbe, 0xf1, 0x6e, 0x09, 0xac, 0x9b, 0xe0, 0x16, 0xbd, 0x3b, 0xf0,
	0x6e, 0x09, 0xec, 0x8a, 0x5b, 0x91, 0x0a, 0x43, 0x87, 0x51, 0x10, 0xf7, 0x98, 0x17, 0xb6, 0x1f,
	0xb9, 0x5e, 0x6b, 0x34, 0x14, 0x1c, 0x2e, 0xd4, 0xe4, 0x6f, 0x17, 0xc6, 0xb5, 0x7e, 0xb4, 0x92,
	0x99, 0xc6, 0xb6, 0x82, 0x56, 0x32, 0x29, 0x0b, 0xb2, 0x67, 0x32, 0x85, 0x8b, 0xf2, 0x2b, 0x97,
	0x07, 0xe5, 0x8b, 0x1a, 0xb2, 0x53, 0x68, 0xb7, 0xd9, 0xf3, 0xed, 0xce, 0x17, 0x16, 0x32, 0x2f,
	0xaa, 0x1a, 0x7b, 0xed, 0x35, 0xf6, 0x5f, 0x5f, 0xe3, 0xe3, 0xc1, 0x15, 0xd5, 0x63, 0x15, 0x38,
	0x2d, 0x79, 0xf0, 0x62, 0xc9, 0xc3, 0x17, 0x4b, 0x86, 0xf3, 0x92, 0x3f, 0x01, 0xf8, 0x0d, 0xbe,
	0xe5, 0x32, 0xa5, 0x23, 0x67, 0xd7, 0x08, 0xf9, 0x00, 0x03, 0xaf, 0x96, 0x92, 0xbe, 0x75, 0x6e,
	0xa9, 0x49, 0x0c, 0x57, 0x09, 0x17, 0xdb, 0xc3, 0xa2, 0x7a, 0xc0, 0x85, 0x8b, 0x9c, 0x63, 0x5b,
	0x71, 0x0d, 0x2d, 0x25, 0xbd, 0x74, 0x5f, 0x78, 0x0a, 0x6d, 0x2a, 0xe5, 0xcf, 0x85, 0x14, 0x29,
	0xd2, 0x2b, 0x9f, 0x3a, 0x81, 0x64, 0x06, 0x24, 0xe5, 0xcf, 0x5f, 0x6b, 0x93, 0x36, 0x7a, 0xed,
	0xa2, 0x2d, 0x0e, 0xf9, 0x0c, 0x63, 0x85, 0xf9, 0x0f, 0x8d, 0x79, 0x2d, 0x3e, 0x76, 0xf1, 0xa6,
	0x41, 0xbe, 0xc0, 0x4d, 0x01, 0xcf, 0xdf, 0x40, 0xdc, 0xc8, 0x7f, 0xdc, 0xc9, 0x2f, 0x20, 0x8d,
	0xbf, 0x4f, 0x93, 0x25, 0x10, 0xd5, 0xa0, 0x34, 0x88, 0x3a, 0xf1, 0xe8, 0x7e, 0xda, 0xf2, 0x53,
	0x34, 0x1e, 0xc1, 0x5a, 0xe6, 0x1f, 0x1f, 0x7e, 0xde, 0x95, 0xf4, 0x56, 0x63, 0xbe, 0x17, 0x2b,
	0x9c, 0xdb, 0x9b, 0xc7, 0xe4, 0x3c, 0xd3, 0x4a, 0xe6, 0xc6, 0xdf, 0x41, 0xb7, 0x1b, 0xcc, 0x8e,
	0x97, 0xd0, 0x53, 0xdf, 0xa1, 0x87, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xe6, 0x13, 0x74,
	0xa3, 0x04, 0x00, 0x00,
}
